[project]
name = "uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "typer>=0.19.2",
    "requests",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
